### ISSUE TITLE
Custom code / xbox 360 racing wheel

### ISSUE THREAD

**Issue by Leizar06001** [ranenbg/Arduino-FFB-wheel#10]
Hi,
Great job ! 
I'm currently trying to modify an old racing wheel I have from the x360, there has never been any driver for the FFB on pc..
So I'd like to do this with as few modification as necessary. This wheel uses one potentiometer instead of an encoder to get it's position so I tried to change bits of your code but I keep getting errors during the compilation, and I tried many things with the files included here, but never get to the end of compilation..
I'm really out of idea now ! :(

**Comment by ranenbg** [comment]
Yeah, getting the code to compile error free is a real pain. When I first took Fernando's code back in 2017 it took me 6 months to figure it out. I do not remember anymore the exact procedure and I was only able to get it to compile on 2 PC's, one with windows 7 and other with windows 10. The Arduino boards version 1.6.21, IDE 1.8.19 You have to replace the original USB core files with the ones present in the BRwheel_my folder. You also have to place it along with all hardware avr core files, I have them in the following folder:
C:\Users\milos\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.6.21\cores\arduino
If there are still errors, then at one more place which I forgot where you have to replace USBCore.h and USBCore.cpp files.
