### ISSUE TITLE
Linux FFB support?

### ISSUE THREAD

**Issue by HanYangZhao** [ranenbg/Arduino-FFB-wheel#12]
Hi,

I was wondering if this will work with Linux with FFB? I have previously build a steering wheel with EMC firmware but the FFB did not work on Linux. The reason I need Linux is because I'm using a Steam Deck as a steering wheel.

Thanks

**Comment by ranenbg** [comment]
I have not tested it under Linux and I'm 99% sure that it will not work since I did not implement the DirectInput API for HID and PID in full. Your best bet is to have a look at openffb firmware for stm32F407.
https://hackaday.io/project/163904-open-ffboard
https://github.com/Ultrawipf/OpenFFBoard
