### ISSUE TITLE
Inverted FFB issue

### ISSUE THREAD

**Issue by EliDev05** [ranenbg/Arduino-FFB-wheel#20]
Hi, congratulations for the project! 
Really well documented, and it's the only Arduino based FBB wheel firmware that is plug and play and user friendly.

I have only one problem, that's on the force feedback direction. When I connect BTS9760 R_PWM and L_PWM pins according to given scheme (so R_PWM to Arduino pin 10 and L_PWM to pin 9) and power up circuit, connect Arduino and open wheel control program, if I turn the wheel to left the motor starts rotating left instead of right, vice versa if I turn the wheel right. 
If I swap R_PWM and L_PWM pins (so pin 10 for L_PWM and pin 9 for R_PWM), the FFB start to working good, so if I turn the wheel to left the motor starts rotating right, trying to re-center the wheel.

My question is if it's a problem swapping the R_PWM and L_PWM pins or maybe there is an "Invert FFB" option somewhere. 
I'm using Arduino Leonardo.

Thanks.

**Comment by ranenbg** [comment]
Hi, thank you very much. Do not change Arduino or BTS PWM pins, just swap the motor wires :) It's just a DC motor and it has no polarity so you can connect it the way you want. To invert ffb, you simply reverse motor direction, that's all.
