### ISSUE TITLE
Rename device 

### ISSUE THREAD

**Issue by jwinfieldnz** [ranenbg/Arduino-FFB-wheel#30]
Is it possible to rename how the device appears in Windows from Arduino Leonardo to something like "Handbrake HID"? 

Would it just be a case of changing the name in `add_to_boards.txt` and compiling?

**Comment by ranenbg** [comment]
Yes and yes.

**Comment by jwinfieldnz** [comment]
Doesn't seem to work, unfortunately. I got it to compile okay but the name is stuck with the default, I updated it in boards.txt manually also. Plugged into another PC also to check it wasn't cached in Windows or something. Just in case anyone else tries it.
