### ISSUE TITLE
Raspberry pi pico with arduino firmware support?

### ISSUE THREAD

**Issue by smahdink** [ranenbg/Arduino-FFB-wheel#31]
As the title says, will this project work on a pico that runs arduino firmware and is flashed with this?
Thanks

**Comment by ranenbg** [comment]
Hi, that's an interesting idea. I didn't try this myself so I have no idea if it would work, You can give it a try and please let me know how did it go.

However, I'd be very surprised if it would go without any compiler error, after all, these are two very different MCUs.
