### ISSUE TITLE
X Axis troubleshooting (?)

### ISSUE THREAD

**Issue by tote46** [ranenbg/Arduino-FFB-wheel#33]
Hello, i having a problem with games reading X axis (encoder axis i guess), both in AFFB GUI and some other apps like WheelCheck, DlView,DxTweak and even in windows calibration X axis is read, but it seems like games (Automobilista 2 and F1 2023) cant read it for some reason.
Leonardo board and analog inputs are readed and work just fine, i made some pedals with hall sensors and potentiometers and they work fine in both games.
What can i do?

**Comment by ranenbg** [comment]
Hi, give it a try with new firmware HEX v230x and wheel control 2.6.0 and see if this helps. It seems like a non-firmware related problem, more like something to do with the automobilista 2 if windows and both wheel control report X axis movement correctly.
