### ISSUE TITLE
Reversed motor polarity

### ISSUE THREAD

**Issue by duce1nik** [ranenbg/Arduino-FFB-wheel#45]
I am having issue with x axis just spin in the direction after I turn the wheel and it don’t stop. 
For example, the steering wheel is center.  If I turn it to the right the steering wheel would just spin in right direction and do not stop.  I would center it again and turn left and it would turn in left direction and without stopping.  I am would expect it to turn back to center at 0 degree if I turn it in either direction.  Please help.

**Comment by ranenbg** [comment]
Hi, your motor is connected in reverse. Just swap wire polarity on it and it will be fine.

**Comment by duce1nik** [comment]
That fixed.  Thank you @ranenbg

**Comment by ranenbg** [comment]
You're welcome, take care.
