### ISSUE TITLE
pmw + dip problem

### ISSUE THREAD

**Issue by Envi4** [ranenbg/Arduino-FFB-wheel#54]
Hi, before that, there was an affb firmware. I decided to switch to your new one, but I have a problem with PWM + dim. I only have single-way recoil, but everything works fine with PWM, just like it does on the affb. Everything works well with PWM + DIP.

**Comment by ranenbg** [comment]
Hi, I'm not sure which problem exactly are you trying to describe. You are talking about pwm+dir mode. Double check if you are taking the direction signal from a correct pin on arduino, as it differs for the 3 supported arduino boards.

**Comment by Envi4** [comment]
PWM+DIR Yes, I'm referring to this mode, but I couldn't get the circuit to work for me. Maybe I connected it incorrectly.

**Comment by ranenbg** [comment]
Yes, that's the first thing you have to check. If you have a multimeter it's very eqsy to mesure dir signals, it's either 0V or 5V, it ahould alternate these two values when ffb changes direction.

**Comment by Envi4** [comment]
![image](https://github.com/ranenbg/Arduino-FFB-wheel/assets/47297400/eeaad0d6-08c5-4239-b725-3cc6587f9bf4)

I have correctly connected everything to the bts7960 itself?

**Comment by ranenbg** [comment]
You are using wrong mode, as bts7960 is a H-bridge type of motor driver that needs 2 channel pwm+- mode. You can set 8kHz, it should be fine. Pins 9 and 10 are the pwm outputs, also make sure to connect 5V (vcc) to pwm enable pins.

**Comment by Envi4** [comment]
Thank you very much, but what kind of board is generally used for pwm + dir

**Comment by ranenbg** [comment]
There are some H-bridge DC motor drivers that use pwm+dir as input, but they are rare. Most of the time, this kind of input is used on 3 phase AC servo motor drivers, or on some 3 phase BLDC drivers. Howerboard motor driver is another example as well.
