### ISSUE TITLE
Support for Arduino UNO R3

### ISSUE THREAD

**Issue by Beocamik** [ranenbg/Arduino-FFB-wheel#55]
I tried uploading Leonardo firmware with Xloader on my Arduino UNO R3 and it don't seen to work. Does Arduino Uno and Leonardo have difference on firmware?

**Comment by ranenbg** [comment]
Hi, you can not upload my firmware on Arduino Uno, it has a completely different microcontroller, that lack's hardware USB HID. It is the essence or magic that makes it work like a joystick in windows.

I pointed out which Arduino boards are supported at the beginning of the github readme. It's leonardo, micro and promicro.

**Comment by Beocamik** [comment]
Okay, thank you very much.
