### ISSUE TITLE
Arduino Nano

### ISSUE THREAD

**Issue by MrCjxer** [ranenbg/Arduino-FFB-wheel#58]
Hi
I want to use an Arduino Nano for button box, but which version I should use?

1 - Arduino Nano CH340
2 - Arduino Nano V3.0
3 - Arduino Nano V3.1
4 - LGT8F328P Nano
5 - Arduino Nano CH340 with ATMEGA168

or all are the same?
or maybe can I use 1 and 2 and 3 except 4 and 5 ?

thank you

**Comment by ranenbg** [comment]
Hi, any nano with ATmega328 will work. They usually come with a Chinese USB-to-serial converter chip CH340, because the MCU does not support it natively.

**Comment by MrCjxer** [comment]
Hi
Thank you

I have a new problem bro 😅🥲
I used FW 230cx.HEX for Leonardo
But when i uploaded it to board and open the GUI, after pass the steps, it goes directly to the main GUI app !

I mean when i choseed the Leonardo at this step :

![Wheel_control_step3](https://github.com/user-attachments/assets/3ff5e1ac-6290-44cd-af11-1a3d9105de34)


It goes to this page :

![Wheel_control_v2_6_0 (2)](https://github.com/user-attachments/assets/4ca2b2de-8418-4800-b04f-a4e32b673984)


I want config the AXIS and buttons or others like this :

![Wheel_control_gamecontrols_setup](https://github.com/user-attachments/assets/e36e43a9-066b-4a7d-b519-fca10339342e)

What should i do ? 🤔

**Comment by ranenbg** [comment]
Hi, you're welcome. Please, don't abuse this issue with another question, if I already answered what you needed in the first place. You close this one as solved and then make a new issue with a new question. I will answer your new question this time and close the issue. If you still have questions, please make a new issue.

This is not a problem what you're showing, this is how I designed my firmware/software. It's supposed to work like that, as you only need to configure the pink window once correctly on a single PC and that's it. This is just the link that makes sure you're using my firmware with my GUI. On the left side there are inputs that my GUI is expecting to see and in the right side is the actual HID device (usualy arduino with some of my HEX), but in general it may be any other joystick that exists. In principle, you can link any GUI axis with any HID axis, or any GUI button with any HID button, but that's simply irrelevant, as in your games you can map any axis or button to any function that you would like. Only for the sake of simplicity, I've put an example of how a pink window should be linked, to avoid confusion, as you can map axis to a button for example , or button to hat switch and so on..It is possible to reset the config such that you do the pink window again, but I'm not gonna explain that here at this moment.
