### ISSUE TITLE
How would i make this work without a motor driver

### ISSUE THREAD

**Issue by n00dlephr0g** [ranenbg/Arduino-FFB-wheel#63]
Not really an issue but a question..
the title may make this seem silly, but i plan on building a sort of hand held steering device along with analogue pedals all within the form factor of a controller, and this means that i wont need that much torque or power.
Is there any way to just drive a small dc motor with a pwm signal or something similar? if not what would be a good alternative to the massive motor driver?

**Comment by ranenbg** [comment]
Hi, you can try to use L298N, you can't power the motor directly from arduino pwm pins as it will probably burn.

I'm not sure what is your form factor, but an h-bridge is a very simple circuit to make, that requires only 4 transistors. I just did a quick google search and there are a ton of available circuits, ranging from simple to more advances with its own microcontroler. I'm guessing you will do your own pcb to place some buttons and arduino, so you could easily integrate an h-bridge into it.
