### ISSUE TITLE
its me again with FFB matters

### ISSUE THREAD

**Issue by Notriatv** [ranenbg/Arduino-FFB-wheel#69]
hi. 
1. I have 15nm with my belt drive wheelbase (or even more... there are some dangerous peaks sometimes). While Windows is booting, I avoid touching the steering wheel because if I do, it starts to cycle like crazy. Actually, I have a power supply switch and turn it on just after the booting process to avoid hurting myself lol. Does this happen to you too?

2. In some games like Assetto Corsa and many others, I can't change FFB filters or anything (even open Wheel Control GUI) while the game is minimized. If I do, I lose FFB, although everything else works fine.. The solution is to restart the game. (it used to happen with AI-wave wheel config too) ETS is one of the few games not affected by opening Wheel Control while playing.

3. It's not really a question, but I noticed that the friction slider really helps remove back EMF feeling from motor, making it really soft. Any value between 199-101 gradually makes it softer, with 101 being the softest and the wheel starts to "overshoot." As you increase to 200, it becomes heavier, while values below 100-0 make steering even heavier. It's a bit confusing, but I found a good range for me (170-190). It depends on other parameters like general gain/pwm frequency, etc.

thank you again!! Cheers!

**Comment by ranenbg** [comment]
1. yes, best is to first plug in arduino once win boots, then turn on psu for motor
2. not sure why this is happening, again, not much I can do about it, if the game takes over the com ports
3. this seems wierd, friction effect should always make wheel more heavier, I need to have a look why it becomes softer above 100% on friction gain slider, tnx for reporting this

Cheers man
