### ISSUE TITLE
I couldn't find the Arduino folder 

### ISSUE THREAD

**Issue by Eyadserry** [ranenbg/Arduino-FFB-wheel#71]
While compiling the software I reached the part where I needed to go to C/users/(username)/ local/ Arduino at that point I couldn't find the Arduino folder neither Arduino15 or any Arduino related folder I made sure that "show hidden folders" option was selected and tried to re install the Arduino boards and the Arduino IDE but it's was useless when I asked for help from someone who said that he is using your software I told me neither he could find that folder at he continued the steps and the software worked fine that's what I did too and it worked, so I'm asking you if this is gonna effect the efficiency in the future? , if yes how to solve it ?

**Comment by ranenbg** [comment]
Hi, I don't know why those folders are not present in your PC. A few people did manage to compile the source themselves following those instructions already. 

I did try a few times to find a way of how to utilize modified arduino core in a more elegant manner by defining include lines with a specified folder path which contains .cpp and .h, without succsess. For the past 6 years, I was hoping that someone will eventualy figure it out and help with this, and I still do. This is as far as could get on my own.
