### ISSUE TITLE
Dúvida 

### ISSUE THREAD

**Issue by Giraita** [ranenbg/Arduino-FFB-wheel#72]
Hello, I used your firmware, which is very good, by the way. Recently, I got an STM32 and switched to OpenFFBoard, but there's a problem: Open works with a range of ±32k, and I would need it to be 0 to 65k. Could you explain how you achieved this? I’m willing to edit Open's firmware!

**Comment by ranenbg** [comment]
Hi, you're welcome.

I have simply changed axis range in HID.cpp and then before sending the USB input report I add 32k to a variable for that particular axis.

**Comment by Giraita** [comment]
Thank you !
