### ISSUE TITLE
problem with buttons

### ISSUE THREAD

**Issue by Eyadserry** [ranenbg/Arduino-FFB-wheel#74]
I don't know if this is a problem. When one button is pressed and I try to press another button, the other button doesn't work. Instead, the first button toggles .

**Comment by ranenbg** [comment]
Hi, what firmware are you using? Which buttons? Are you talking about buttons on arduino, or nano or button matrix?

**Comment by Eyadserry** [comment]
v240chtx, I'm using the button matrix on leonardo.

**Comment by ranenbg** [comment]
Yeah, not sure, doesn't sound like normal operation that I intended, will need to investigate. Tnx for eporting it.

**Comment by Eyadserry** [comment]
https://github.com/user-attachments/assets/fd9dda26-ab4d-487e-8a85-6571e560e8b5

As you can see in the video, I pressed button number 8. While it was pressed, I also pressed button number 0, and then button 8 started toggling. When I released my finger from button 8, button 0 lit up. I did the same thing again."

**Comment by Eyadserry** [comment]
if you have other questions to solve the problem, I would be pleased to answer.

**Comment by ranenbg** [comment]
Tnx, for now this is enough info.

**Comment by Eyadserry** [comment]
ok, I'm gonna close the issue.
