### ISSUE TITLE
Some New Questions

### ISSUE THREAD

**Issue by etempm** [ranenbg/Arduino-FFB-wheel#8]
Hi again,

I am planing to build wheel with rs997 motor (more bigger one) and bts7960 as I said before. Here I have some questions about build.

1) Is it possible to use AS5600 magnetic encoder (4000ppr) with firmware. It is cheap and more resolution (12bit)
2) Is it possible to use loadcell for brake and throttle pedal together
3) Because of big motor, it will be nice to read currents from BTS. Is there a support in firmware about this 

Thanks you again.

**Comment by ranenbg** [comment]
Hi man, here are the answers:
1. yes, but I do not plan to do it any time soon
2. probably, you have to do this in the game somehow, I do not plan to implement that in the firmware
3. there is no need to waste main mcu time for this, you can just use a separate arduino and read these voltages and display it on some LCD
